### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
You can try the Docker image from the link below.
https://hub.docker.com/r/daisukeyoshimoto/activiti-cloud-modeling-standalone

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
@popovicsandras 

I was instructed by Salaboy to be reviewed from you. Can you confirm this PR?

This PR combines front-end and back-end of activiti-modeling-app into one Spring Boot application and can be used as one Docker container so that developers can easily use activiti-modeling-app locally.

However, when combining it into the Spring Boot application, some front-end part have been customized because it could not correspond to the authentication method (OpenId) required by the activit-modeling-app frontend.Specifically, it is the following difference.
https://github.com/Activiti/activiti-modeling-app/compare/basic-auth

**Comment by popovicsandras** [comment]
Hi @daisuke-yoshimoto,

It is strange you were forwarded to me, since all I can see here are files related to Docker and some Java classes. And I don't know too much about the context either. (my last info about this `authentication-less` or `desktop version` was that is was temporary postponed, wasn't it @salaboy ?)
I'd be happy to review and approve this for you, however I don't think I'm the most competent resource to do it, I take more responsibility on the frontend part, and unfortunately I have limited knowledge on the parts you changed.

Maybe @mteodori or @ffazzini can help us to have this PR approved?

**Comment by daisuke-yoshimoto** [comment]
@salaboy 
Can you check this PR?

**Comment by salaboy** [comment]
@popovicsandras this is a community effort to make things better for all of us. I referred it to you because you know about the front end. Community efforts are done with best intentions by community people like @daisuke-yoshimoto who offers his own personal time to help us and make the project better. We usually try to help them to get things done. This is how overall we improve community and enterprise software, by accommodating new use cases and adding extensions to our code to support different environments.

**Review by salaboy — APPROVED** [review]
this can be merged

**Comment by salaboy** [comment]
@daisuke-yoshimoto awesome stuff.. this seems to be working.. next step is to try to implement a filesystem layer for the backend

**Comment by popovicsandras** [comment]
@salaboy, @daisuke-yoshimoto, sorry, maybe my answer was not clear enough. I know and really appreciate the community effort and everytime there is a PR which I'm competent about, I'm more than happy to give a review as I have done it already.
The only problem with this PR was me and my knowledge. Simply I don't know anything about the docker and Java side of this application, and in this PR there was no frontend related code, which I could approve. But again, whenever in the future there is a PR which I'm competent to review or discuss, I'm happy to do it.

**Comment by salaboy** [comment]
@popovicsandras from a community point of view.. can we think about different things to plug authentication mechanisms? I think that @daisuke-yoshimoto was trying to find out if basic auth can be supported from the front end to not add too many changes for this standalone approach.

**Comment by daisuke-yoshimoto** [comment]
@popovicsandras @salaboy 

> I think that @daisuke-yoshimoto was trying to find out if basic auth can be supported from the front end to not add too many changes for this standalone approach.

In this repository(this pr), in order to support authentication other than OpenId, some part of activiti-modeling-app is customized. Specifically, it is the following diff.
https://github.com/Activiti/activiti-modeling-app/compare/basic-auth

If possible, please merge this fix into activiti-modeling-app's master branch. Otherwise, we will need to keep merging master branch modifications into basic-auth branch.
https://github.com/Activiti/activiti-modeling-app/tree/basic-auth

The above fix is just to support alfresco-js-api's basic authentication mode.
https://github.com/Alfresco/alfresco-js-api

**Comment by salaboy** [comment]
@popovicsandras I think that it wasn't 100% clear before, neither myself or @daisuke-yoshimoto but we will appreciate some thoughts on those Front end changes related to the front end app.

**Comment by popovicsandras** [comment]
@salaboy @daisuke-yoshimoto As previously discussed on Slack, please let's have a meeting with all of us, to let me know the bigger scope of this story, why we need this modification. For the PR as it is, I can't approve it yet unfortunately, the app.config.json has to be untouched.

Regarding the role guard and request helper, what I see from the PR:
If we want to bypass the authorisation, I don't think we should hack and use the basic authorisation for it, especially not with the ecmClient, which is there for the content service. At least if I understood correctly what was the purpose of that code snippet.

As I see, we should rather implement another strategy similar to the `AmaRoleGuard`. We could have something like `LenientGuard`, which simply bypasses the authorisation check, and to use it, we can even introduce a flag either in the app.config.json or maybe inside the environment files. If we set this `auth` flag to false, we could wire the application to use the `LenientGuard` instead of the `AmaRoleGuard`.

But this adds some more things to consider, like do we need authentication (login screen) if we don't need authorisation, whether these two should be handled separately, etc... (at least these are the topics I remember from our last discussion about the standalone application).

Just some ideas.
But as I said, I need to know more about this to see what we would like to achieve here.

**Comment by daisuke-yoshimoto** [comment]
@popovicsandras 

>  the app.config.json has to be untouched.

Sorry. I will revert this fix.

> If we want to bypass the authorisation, I don't think we should hack and use the basic authorisation for it, especially not with the ecmClient, which is there for the content service. At least if I understood correctly what was the purpose of that code snippet.

Please check the diff URL . I use bpmClient instead of ecmClient.
https://github.com/Activiti/activiti-modeling-app/compare/basic-auth

**Comment by daisuke-yoshimoto** [comment]
@popovicsandras @salaboy 

> But this adds some more things to consider, like do we need authentication (login screen) if we don't need authorisation, whether these two should be handled separately, etc... (at least these are the topics I remember from our last discussion about the standalone application).

As it is a web application, authentication itself will be necessary. Stand-alone is a nuance that makes it easy to build an environment. I think that it is assumed that it is used by two or more people.

I think the mode that does not require authentication is for client applications (electron).

**Comment by daisuke-yoshimoto** [comment]
@popovicsandras 

> As I see, we should rather implement another strategy similar to the AmaRoleGuard. We could have something like LenientGuard, which simply bypasses the authorisation check, and to use it, we can even introduce a flag either in the app.config.json or maybe inside the environment files. If we set this auth flag to false, we could wire the application to use the LenientGuard instead of the AmaRoleGuard.

Thanks. Please add the setting to app.config.json. However, I feel that the meaning of the correction I added is the same. In my fix, I do not check AmaRoleGuard if app.config.json authentication type is basic

**Pull request merged**
